name: Backend Build Check

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  
  build:
    runs-on: ubuntu-latest  

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  

      
      - name: Navigate to backend folder
        run: cd backend

      
      - name: Install dependencies
        run: |
          cd backend
          npm install

      
      - name: Build TypeScript Project
        run: |
          cd backend
          npm run build  

      
      - name: Check TypeScript Configuration
        run: |
          cd backend
          npx tsc --noEmit  
